apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j
  namespace: value-fabric
$patch: delete
---
apiVersion: v1
kind: Service
metadata:
  name: neo4j
  namespace: value-fabric
$patch: delete
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-data-pvc
  namespace: value-fabric
$patch: delete
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-logs-pvc
  namespace: value-fabric
$patch: delete
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: neo4j-pdb
  namespace: value-fabric
$patch: delete
