"""Executable canonical platform contract surfaces for Fabric 4L."""

from .agent_output import AgentErrorDetail, AgentResultEnvelope, AgentResultMetadata
from .context import (
    AUTH_SOURCE_API_KEY,
    AUTH_SOURCE_JWT,
    AUTH_SOURCE_SERVICE_ACCOUNT,
    AUTH_SOURCE_UNKNOWN,
    ISOLATION_TIER_DATABASE,
    ISOLATION_TIER_SCHEMA,
    ISOLATION_TIER_SHARED,
    ContextContractError,
    RequestContext,
    clear_current_context,
    get_current_context,
    get_request_context,
    require_context,
    set_current_context,
    set_request_context,
)
from .database import (
    RESERVED_TENANT_KEYWORDS,
    SessionFactoryNotConfiguredError,
    SessionLifecycleError,
    TenantContextError,
    UnsupportedIsolationTierError,
    clear_session_factory,
    db_session_for_context,
    get_db_from_context,
    set_session_factory,
    set_tenant_context,
    validate_tenant_id,
)
from .tool_boundary import (
    BaseTool,
    ToolContractError,
    ToolNotFoundError,
    ToolRegistrationError,
    ToolRegistry,
    ToolValidationError,
)

__all__ = [
    "AUTH_SOURCE_API_KEY",
    "AUTH_SOURCE_JWT",
    "AUTH_SOURCE_SERVICE_ACCOUNT",
    "AUTH_SOURCE_UNKNOWN",
    "AgentErrorDetail",
    "AgentResultEnvelope",
    "AgentResultMetadata",
    "BaseTool",
    "ContextContractError",
    "ISOLATION_TIER_DATABASE",
    "ISOLATION_TIER_SCHEMA",
    "ISOLATION_TIER_SHARED",
    "RESERVED_TENANT_KEYWORDS",
    "RequestContext",
    "SessionFactoryNotConfiguredError",
    "SessionLifecycleError",
    "TenantContextError",
    "ToolContractError",
    "ToolNotFoundError",
    "ToolRegistrationError",
    "ToolRegistry",
    "ToolValidationError",
    "UnsupportedIsolationTierError",
    "clear_current_context",
    "clear_session_factory",
    "db_session_for_context",
    "get_current_context",
    "get_db_from_context",
    "get_request_context",
    "require_context",
    "set_current_context",
    "set_request_context",
    "set_session_factory",
    "set_tenant_context",
    "validate_tenant_id",
]
