#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SECRETS_DIR="${ROOT_DIR}/.local/secrets"
ENV_FILE="${SECRETS_DIR}/dev.env"
TTL_DAYS="${TTL_DAYS:-7}"

mkdir -p "${SECRETS_DIR}"
chmod 700 "${ROOT_DIR}/.local" "${SECRETS_DIR}" 2>/dev/null || true

rand_hex() {
  openssl rand -hex "${1:-32}"
}

issued_at="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
expires_at="$(date -u -d "+${TTL_DAYS} days" +%Y-%m-%dT%H:%M:%SZ 2>/dev/null || python - <<'PY'
from datetime import datetime, timedelta, timezone
print((datetime.now(timezone.utc)+timedelta(days=7)).strftime('%Y-%m-%dT%H:%M:%SZ'))
PY
)"

cat > "${ENV_FILE}" <<EOF
# Ephemeral local secrets generated by scripts/security/bootstrap_local_secrets.sh
# Rotate by rerunning this script; intended TTL ${TTL_DAYS} days.
SECRETS_ISSUED_AT=${issued_at}
SECRETS_EXPIRES_AT=${expires_at}
OPENAI_API_KEY=sk-local-$(rand_hex 24)
ANTHROPIC_API_KEY=ant-local-$(rand_hex 24)
NEO4J_PASSWORD=$(rand_hex 16)
POSTGRES_PASSWORD=$(rand_hex 16)
JWT_SECRET=$(rand_hex 32)
REDIS_PASSWORD=$(rand_hex 16)
EOF

chmod 600 "${ENV_FILE}"

echo "Wrote ephemeral local env file: ${ENV_FILE}"
echo "To rotate secrets, rerun: scripts/security/bootstrap_local_secrets.sh"
