"""Layer 1 import-hygiene gate.

Blocks new production imports from ``value_fabric.layer1`` outside an
explicit allowlist.  Run as a CI step or locally:

    python scripts/ci/check_layer1_imports.py --strict

Exit 0 when clean, 1 when violations found.
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]

# Patterns that match ``value_fabric.layer1`` imports.
IMPORT_PATTERNS = [
    re.compile(r"\bfrom\s+value_fabric\.layer1\b"),
    re.compile(r"\bimport\s+value_fabric\.layer1\b"),
]

# Files and directories that are allowed to reference value_fabric.layer1.
ALLOWLIST: set[str] = {
    # Shim files
    "value_fabric/layer1/__init__.py",
    "value_fabric/layer1/crawler/__init__.py",
    # ADR and governance docs
    "docs/architecture/adr-027-layer3-canonical-path.md",
    "docs/reference/layer-runtime-path-governance.md",
    # CI and contract tests that intentionally verify the shim
    "tests/arch/test_canonical_module_sentinels.py",
    "tests/contract/test_import_topology.py",
    "tests/ci/test_launch_readiness_workflow.py",
    # Cross-layer integration / security tests (legacy, await migration)
    "tests/context/test_tenant_context_contract.py",
    "tests/security/conftest.py",
    "tests/security/test_cross_layer_tenant.py",
    "tests/security/test_cross_layer_tenant_isolation_matrix.py",
    "tests/security/test_p1_20_xxe_prevention.py",
    "tests/security/test_security_fixes.py",
    # Layer 1 test suite (legacy imports; individual migration tracked in ADR-027)
    "services/layer1-ingestion/tests/",
    # This script itself
    "scripts/ci/check_layer1_imports.py",
    # Migration report (generated by this effort)
    "reports/layer1-import-migration-2026-05-13.md",
}

# Directories that are never scanned (cache, venv, etc.)
SKIP_DIRS = {
    ".venv",
    "venv",
    "node_modules",
    "__pycache__",
    ".pytest_cache",
    ".git",
    ".hypothesis",
    ".ruff_cache",
    ".mypy_cache",
    ".uv-cache-local",
}


def _is_allowed(rel_path: str) -> bool:
    """Return True when *rel_path* is in the allowlist or inside an allowed dir."""
    if rel_path in ALLOWLIST:
        return True
    # Allow anything under value_fabric/layer1/ (shim tree)
    if rel_path.startswith("value_fabric/layer1/"):
        return True
    # Allow anything under directory entries in ALLOWLIST
    for allowed in ALLOWLIST:
        if allowed.endswith("/") and rel_path.startswith(allowed):
            return True
    return False


def _find_violations(*, scan_roots: list[Path]) -> list[str]:
    violations: list[str] = []
    for scan_root in scan_roots:
        if not scan_root.exists():
            continue
        for dirpath, dirnames, filenames in os.walk(scan_root):
            dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS]
            for fname in filenames:
                if not fname.endswith(".py"):
                    continue
                py_file = Path(dirpath) / fname
                rel_path = py_file.relative_to(REPO_ROOT).as_posix()
                if _is_allowed(rel_path):
                    continue
                content = py_file.read_text(encoding="utf-8")
                for pattern in IMPORT_PATTERNS:
                    if pattern.search(content):
                        violations.append(rel_path)
                        break
    return violations


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Layer 1 import-hygiene gate")
    parser.add_argument(
        "--strict",
        action="store_true",
        help="Fail on any violation (default: dry-run report)",
    )
    args = parser.parse_args(argv)

    scan_roots = [
        REPO_ROOT / "services",
        REPO_ROOT / "value_fabric",
        REPO_ROOT / "scripts",
        REPO_ROOT / "tests",
    ]
    violations = _find_violations(scan_roots=scan_roots)

    if violations:
        print("Layer 1 import-hygiene violations found:")
        for v in violations:
            print(f"  - {v}")
        print(
            "\nThese files import value_fabric.layer1 outside the allowlist. "
            "Migrate to direct service-path imports or add to ALLOWLIST."
        )
        if args.strict:
            return 1
    else:
        print("No Layer 1 import-hygiene violations found.")

    return 0


if __name__ == "__main__":
    sys.exit(main())
