"""Layer 3 import-hygiene gate.

Blocks new production imports from ``value_fabric.layer3`` outside an
explicit allowlist. Also blocks legacy namespace imports for
``value_fabric.layer3_knowledge`` which was removed per ADR-027 cleanup.

Run as a CI step or locally:

    python scripts/ci/check_layer3_imports.py --strict

Exit 0 when clean, 1 when violations found.
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]

# Patterns that match ``value_fabric.layer3`` imports.
IMPORT_PATTERNS = [
    re.compile(r"\bfrom\s+value_fabric\.layer3\b"),
    re.compile(r"\bimport\s+value_fabric\.layer3\b"),
]

# Legacy namespace imports that must not be reintroduced after cleanup.
LEGACY_NAMESPACE_PATTERNS = [
    re.compile(r"\bfrom\s+value_fabric\.layer3_knowledge\b"),
    re.compile(r"\bimport\s+value_fabric\.layer3_knowledge\b"),
]
LEGACY_TENANT_DEP_PATTERN = re.compile(r"\bfrom\s+.*dependencies_tenant\s+import\b")

# Directories that must remain empty (or not exist) after cleanup.
DEAD_DIRECTORIES = {
    "value_fabric/layer3_knowledge",
}

# After ADR-027 migration, these directories must contain only the __init__.py shim.
SHIM_ONLY_DIRECTORIES = {
    "value_fabric/layer3",
}

# Files and directories that are allowed to reference value_fabric.layer3.
ALLOWLIST: set[str] = {
    # Shim files
    "value_fabric/layer3/__init__.py",
    # ADR and governance docs
    "docs/architecture/adr-027-layer3-canonical-path.md",
    "docs/reference/layer-runtime-path-governance.md",
    # CI and contract tests that intentionally verify the shim
    "tests/arch/test_canonical_module_sentinels.py",
    "tests/contract/test_import_topology.py",
    "tests/ci/test_launch_readiness_workflow.py",
    "tests/ci/test_deprecated_namespace_imports.py",
    "tests/ci/test_check_layer3_wrapper_drift.py",
    # Cross-layer integration / security tests (legacy, await migration)
    "tests/context/test_tenant_context_contract.py",
    "tests/security/conftest.py",
    "tests/security/test_cross_layer_tenant.py",
    "tests/security/test_cross_layer_tenant_isolation_matrix.py",
    "tests/security/test_p1_20_xxe_prevention.py",
    "tests/security/test_security_fixes.py",
    "tests/security/test_layer3_similarity_roi_tenant_isolation.py",
    "tests/security/test_neo4j_cross_tenant_write_isolation.py",
    "tests/security/test_neo4j_tenant_query_enforcement.py",
    "tests/security/test_graph_tenant_hostile_regression.py",
    "tests/performance/test_performance_optimizations.py",
    # Layer 3 canonical service source (internal imports still reference value_fabric.layer3
    # during gradual migration; tracked as technical debt post-ADR-027)
    "services/layer3-knowledge/src/",
    "services/layer3-knowledge/scripts/",
    # Layer 3 test suite (legacy imports; individual migration tracked in ADR-027)
    "services/layer3-knowledge/tests/",
    "tests/layer3/",
    "tests/integration/",
    "tests/evals/",
    "tests/contract/",
    "tests/ci/",
    "tests/cache/",
    "tests/arch/",
    "services/layer4-agents/tests/",
    # This script itself
    "scripts/ci/check_layer3_imports.py",
    "scripts/ci/check_layer3_wrapper_drift.py",
    "scripts/ci/check_layer3_source_mirror.py",
    "scripts/ci/check_layer3_tenant_scoped_similarity_roi.py",
    "scripts/ci/check_layer3_graph_execution_wrappers.py",
    "scripts/ci/check_layer3_query_entrypoints.py",
    "scripts/ci/check_layer3_settings_shim_drift.py",
    "scripts/ci/check_layer3_cypher_scope.py",
    # Migration report (generated by this effort)
    "reports/MIGRATION_HARDENING_REPORT_2026-05-12.md",
}

# Directories that are never scanned (cache, venv, etc.)
SKIP_DIRS = {
    ".venv",
    "venv",
    "node_modules",
    "__pycache__",
    ".pytest_cache",
    ".git",
    ".hypothesis",
    ".ruff_cache",
    ".mypy_cache",
    ".uv-cache-local",
}


def _is_allowed(rel_path: str) -> bool:
    """Return True when *rel_path* is in the allowlist or inside an allowed dir."""
    if rel_path in ALLOWLIST:
        return True
    # Allow anything under value_fabric/layer3/ (shim tree)
    if rel_path.startswith("value_fabric/layer3/"):
        return True
    # Allow anything under directory entries in ALLOWLIST
    for allowed in ALLOWLIST:
        if allowed.endswith("/") and rel_path.startswith(allowed):
            return True
    return False


def _find_violations(*, scan_roots: list[Path]) -> list[str]:
    violations: list[str] = []
    for scan_root in scan_roots:
        if not scan_root.exists():
            continue
        for dirpath, dirnames, filenames in os.walk(scan_root):
            dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS]
            for fname in filenames:
                if not fname.endswith(".py"):
                    continue
                py_file = Path(dirpath) / fname
                rel_path = py_file.relative_to(REPO_ROOT).as_posix()
                if _is_allowed(rel_path):
                    continue
                content = py_file.read_text(encoding="utf-8")
                for pattern in IMPORT_PATTERNS:
                    if pattern.search(content):
                        violations.append(f"{rel_path}: imports value_fabric.layer3")
                        break
                for pattern in LEGACY_NAMESPACE_PATTERNS:
                    if pattern.search(content):
                        violations.append(f"{rel_path}: imports dead namespace (layer3_knowledge)")
                        break
                if rel_path != "services/layer3-knowledge/src/api/dependencies_tenant.py":
                    if LEGACY_TENANT_DEP_PATTERN.search(content):
                        violations.append(
                            f"{rel_path}: imports deprecated Layer 3 tenant dependency shim "
                            "(use dependencies_tenant_secured)"
                        )
    return violations


def _find_dead_directory_reintroductions() -> list[str]:
    """Return violations if dead directories were reintroduced."""
    violations: list[str] = []
    for dead_dir in DEAD_DIRECTORIES:
        path = REPO_ROOT / dead_dir
        if path.exists() and any(path.iterdir()):
            violations.append(f"{dead_dir}: dead directory reintroduced with content")
    return violations


def _find_stale_shim_content() -> list[str]:
    """Return violations if shim-only directories contain implementation files."""
    violations: list[str] = []
    for shim_dir in SHIM_ONLY_DIRECTORIES:
        path = REPO_ROOT / shim_dir
        if not path.exists():
            continue
        for item in path.iterdir():
            if item.name == "__init__.py":
                continue
            if item.name == "__pycache__":
                continue
            if item.is_file():
                violations.append(
                    f"{shim_dir}/{item.name}: stale implementation file in shim directory"
                )
            elif item.is_dir():
                violations.append(
                    f"{shim_dir}/{item.name}/: stale subdirectory in shim directory"
                )
    return violations


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Layer 3 import-hygiene gate")
    parser.add_argument(
        "--strict",
        action="store_true",
        help="Fail on any violation (default: dry-run report)",
    )
    args = parser.parse_args(argv)

    scan_roots = [
        REPO_ROOT / "services",
        REPO_ROOT / "value_fabric",
        REPO_ROOT / "scripts",
        REPO_ROOT / "tests",
    ]
    violations = _find_violations(scan_roots=scan_roots)
    violations.extend(_find_dead_directory_reintroductions())
    violations.extend(_find_stale_shim_content())

    if violations:
        print("Layer 3 import-hygiene violations found:")
        for v in violations:
            print(f"  - {v}")
        print(
            "\nSome files import value_fabric.layer3 outside the allowlist, "
            "or reference dead namespaces, or dead directories were reintroduced. "
            "Migrate to direct service-path imports or add to ALLOWLIST."
        )
        if args.strict:
            return 1
    else:
        print("No Layer 3 import-hygiene violations found.")

    return 0


if __name__ == "__main__":
    sys.exit(main())
