apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pgbouncer-auth
  namespace: value-fabric
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: pgbouncer-auth
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        userlist.txt: "{{ .pgbouncer_userlist }}"
        pgbouncer-health-password: "{{ .pgbouncer_health_password }}"
  data:
    - secretKey: pgbouncer_userlist
      remoteRef:
        key: secret/data/value-fabric/prod/pgbouncer
        property: userlist
    - secretKey: pgbouncer_health_password
      remoteRef:
        key: secret/data/value-fabric/prod/pgbouncer
        property: health-password
