"""Spec-compliant schema migration

Revision ID: 003
Revises: 002
Create Date: 2024-01-01 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '003'
down_revision: Union[str, None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop old tables
    op.drop_index('idx_crawl_queue_domain_priority', table_name='crawl_queue')
    op.drop_index('idx_crawl_queue_job_status', table_name='crawl_queue')
    op.drop_index('idx_crawl_queue_next_retry', table_name='crawl_queue')
    op.drop_index('uq_crawl_queue_job_url', table_name='crawl_queue')
    op.drop_table('crawl_queue')
    
    op.drop_index('idx_crawled_content_domain_extracted', table_name='crawled_content')
    op.drop_index('idx_crawled_content_job_type', table_name='crawled_content')
    op.drop_table('crawled_content')
    
    op.drop_index('idx_audit_logs_domain_action', table_name='audit_logs')
    op.drop_index('idx_audit_logs_timestamp', table_name='audit_logs')
    op.drop_table('audit_logs')
    
    op.drop_index('idx_crawl_jobs_status_created', table_name='crawl_jobs')
    op.drop_table('crawl_jobs')
    
    # Create new tables
    op.create_table('scraping_targets',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=False, index=True),
        sa.Column('name', sa.String(255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('url', sa.Text(), nullable=False),
        sa.Column('url_pattern', sa.String(500), nullable=True),
        sa.Column('target_type', sa.String(50), nullable=False, server_default='SINGLE_PAGE'),
        sa.Column('extraction_config', postgresql.JSONB(), server_default='{}'),
        sa.Column('browser_config', postgresql.JSONB(), server_default='{}'),
        sa.Column('schedule', postgresql.JSONB(), nullable=True),
        sa.Column('rate_limit', postgresql.JSONB(), server_default='{}'),
        sa.Column('compliance', postgresql.JSONB(), server_default='{}'),
        sa.Column('proxy_config', postgresql.JSONB(), server_default='{}'),
        sa.Column('authentication', postgresql.JSONB(), nullable=True),
        sa.Column('status', sa.String(50), nullable=False, server_default='ACTIVE'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), onupdate=sa.text('now()'), nullable=False),
        sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('last_error_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('success_count', sa.Integer(), server_default='0'),
        sa.Column('error_count', sa.Integer(), server_default='0'),
        sa.Column('average_execution_time_ms', sa.Integer(), server_default='0'),
        sa.Column('tags', postgresql.JSONB(), server_default='[]'),
    )
    op.create_index('idx_scraping_targets_org_status', 'scraping_targets', ['organization_id', 'status'])
    op.create_index('idx_scraping_targets_created', 'scraping_targets', ['organization_id', 'created_at'])
    
    op.create_table('scraping_jobs',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=False, index=True),
        sa.Column('target_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('scraping_targets.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('configuration', postgresql.JSONB(), server_default='{}'),
        sa.Column('status', sa.String(50), nullable=False, server_default='PENDING', index=True),
        sa.Column('priority', sa.Integer(), server_default='5'),
        sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('estimated_duration_ms', sa.Integer(), nullable=True),
        sa.Column('progress_total_pages', sa.Integer(), nullable=True),
        sa.Column('progress_processed_pages', sa.Integer(), server_default='0'),
        sa.Column('progress_failed_pages', sa.Integer(), server_default='0'),
        sa.Column('progress_current_url', sa.Text(), nullable=True),
        sa.Column('progress_stage', sa.String(50), server_default='INIT'),
        sa.Column('progress_percent_complete', sa.Integer(), server_default='0'),
        sa.Column('results_raw_content_count', sa.Integer(), server_default='0'),
        sa.Column('results_extracted_record_count', sa.Integer(), server_default='0'),
        sa.Column('results_storage_bytes_used', sa.Integer(), server_default='0'),
        sa.Column('results_output_location', sa.Text(), nullable=True),
        sa.Column('resources_browser_sessions_used', sa.Integer(), server_default='0'),
        sa.Column('resources_proxy_requests_made', sa.Integer(), server_default='0'),
        sa.Column('resources_llm_tokens_consumed', sa.Integer(), server_default='0'),
        sa.Column('resources_compute_time_ms', sa.Integer(), server_default='0'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('triggered_by', sa.String(50), server_default='MANUAL'),
        sa.Column('correlation_id', sa.String(100), nullable=True),
    )
    op.create_index('idx_scraping_jobs_org_status', 'scraping_jobs', ['organization_id', 'status'])
    op.create_index('idx_scraping_jobs_target', 'scraping_jobs', ['target_id', 'created_at'])
    op.create_index('idx_scraping_jobs_status_created', 'scraping_jobs', ['status', 'created_at'])
    
    op.create_table('job_stage_details',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('job_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('scraping_jobs.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=False, index=True),
        sa.Column('stage', sa.String(50), nullable=False),
        sa.Column('status', sa.String(50), nullable=False, server_default='PENDING'),
        sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('duration_ms', sa.Integer(), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('metadata', postgresql.JSONB(), server_default='{}'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.UniqueConstraint('job_id', 'stage', name='uq_job_stage'),
    )
    op.create_index('idx_job_stage_details_job_stage', 'job_stage_details', ['job_id', 'stage'])
    
    op.create_table('job_errors',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('job_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('scraping_jobs.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=False, index=True),
        sa.Column('stage', sa.String(50), nullable=False),
        sa.Column('error_code', sa.String(100), nullable=False),
        sa.Column('error_message', sa.Text(), nullable=False),
        sa.Column('stack_trace', sa.Text(), nullable=True),
        sa.Column('url', sa.Text(), nullable=True),
        sa.Column('retryable', sa.Boolean(), server_default='true'),
        sa.Column('retry_count', sa.Integer(), server_default='0'),
        sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('resolution', sa.Text(), nullable=True),
    )
    op.create_index('idx_job_errors_job_occurred', 'job_errors', ['job_id', 'occurred_at'])
    op.create_index('idx_job_errors_retryable', 'job_errors', ['retryable', 'retry_count'])
    
    op.create_table('raw_content',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('job_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('scraping_jobs.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=False, index=True),
        sa.Column('target_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('scraping_targets.id', ondelete='SET NULL'), nullable=True, index=True),
        sa.Column('source_url', sa.Text(), nullable=False),
        sa.Column('source_final_url', sa.Text(), nullable=True),
        sa.Column('source_domain', sa.String(255), nullable=False, index=True),
        sa.Column('source_ip_address', sa.String(45), nullable=True),
        sa.Column('source_accessed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('source_http_status', sa.Integer(), nullable=True),
        sa.Column('source_headers', postgresql.JSONB(), server_default='{}'),
        sa.Column('source_content_type', sa.String(255), nullable=True),
        sa.Column('source_content_length', sa.Integer(), nullable=True),
        sa.Column('storage_html_path', sa.Text(), nullable=True),
        sa.Column('storage_screenshot_path', sa.Text(), nullable=True),
        sa.Column('storage_dom_snapshot_path', sa.Text(), nullable=True),
        sa.Column('storage_har_path', sa.Text(), nullable=True),
        sa.Column('storage_text_content_path', sa.Text(), nullable=True),
        sa.Column('meta_title', sa.Text(), nullable=True),
        sa.Column('meta_description', sa.Text(), nullable=True),
        sa.Column('meta_language', sa.String(10), nullable=True),
        sa.Column('meta_charset', sa.String(50), nullable=True),
        sa.Column('meta_viewport', sa.String(255), nullable=True),
        sa.Column('meta_canonical_url', sa.Text(), nullable=True),
        sa.Column('meta_robots_meta', sa.String(255), nullable=True),
        sa.Column('meta_og_tags', postgresql.JSONB(), server_default='{}'),
        sa.Column('meta_structured_data', postgresql.JSONB(), server_default='[]'),
        sa.Column('capture_method', sa.String(50), server_default='DYNAMIC'),
        sa.Column('capture_browser_version', sa.String(100), nullable=True),
        sa.Column('capture_rendering_engine', sa.String(100), nullable=True),
        sa.Column('capture_javascript_executed', sa.Boolean(), server_default='true'),
        sa.Column('capture_wait_time_ms', sa.Integer(), server_default='0'),
        sa.Column('capture_scroll_depth', sa.Integer(), nullable=True),
        sa.Column('capture_interactions', postgresql.JSONB(), server_default='[]'),
        sa.Column('content_hash', sa.String(64), nullable=True, index=True),
        sa.Column('is_duplicate', sa.Boolean(), server_default='false'),
        sa.Column('duplicate_of_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('raw_content.id', ondelete='SET NULL'), nullable=True),
        sa.Column('processing_status', sa.String(50), server_default='PENDING'),
        sa.Column('extracted_data_id', postgresql.UUID(as_uuid=True), nullable=True, index=True),
        sa.Column('retention_raw_content_expiry_days', sa.Integer(), server_default='30'),
        sa.Column('retention_screenshot_expiry_days', sa.Integer(), server_default='30'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    )
    op.create_index('idx_raw_content_job_status', 'raw_content', ['job_id', 'processing_status'])
    op.create_index('idx_raw_content_org_domain', 'raw_content', ['organization_id', 'source_domain'])
    op.create_index('idx_raw_content_hash', 'raw_content', ['organization_id', 'content_hash'])
    
    op.create_table('extracted_data',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('job_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('scraping_jobs.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('raw_content_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('raw_content.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=False, index=True),
        sa.Column('target_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('scraping_targets.id', ondelete='SET NULL'), nullable=True, index=True),
        sa.Column('extraction_method', sa.String(50), nullable=False),
        sa.Column('extraction_llm_model', sa.String(100), nullable=True),
        sa.Column('extraction_prompt_version', sa.String(50), nullable=True),
        sa.Column('extraction_time_ms', sa.Integer(), server_default='0'),
        sa.Column('extraction_confidence_score', sa.Numeric(3, 2), server_default='0.00'),
        sa.Column('extraction_schema_version', sa.String(50), nullable=True),
        sa.Column('data', postgresql.JSONB(), server_default='{}'),
        sa.Column('validation_schema_valid', sa.Boolean(), server_default='true'),
        sa.Column('validation_errors', postgresql.JSONB(), server_default='[]'),
        sa.Column('validation_required_fields_present', postgresql.JSONB(), server_default='[]'),
        sa.Column('validation_required_fields_missing', postgresql.JSONB(), server_default='[]'),
        sa.Column('validation_data_quality_score', sa.Numeric(3, 2), server_default='0.00'),
        sa.Column('provenance_source_url', sa.Text(), nullable=False),
        sa.Column('provenance_extracted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('provenance_extraction_version', sa.String(50), nullable=True),
        sa.Column('post_pii_redaction_applied', sa.Boolean(), server_default='false'),
        sa.Column('post_redacted_fields', postgresql.JSONB(), server_default='[]'),
        sa.Column('post_normalized_fields', postgresql.JSONB(), server_default='[]'),
        sa.Column('post_enriched_fields', postgresql.JSONB(), server_default='[]'),
        sa.Column('ontology_concept_ids', postgresql.JSONB(), server_default='[]'),
        sa.Column('ontology_relationship_ids', postgresql.JSONB(), server_default='[]'),
        sa.Column('ontology_mapped_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('ontology_mapping_confidence', sa.Numeric(3, 2), nullable=True),
        sa.Column('storage_path', sa.Text(), nullable=True),
        sa.Column('format', sa.String(20), server_default='JSON'),
        sa.Column('size_bytes', sa.Integer(), server_default='0'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), onupdate=sa.text('now()'), nullable=False),
    )
    op.create_index('idx_extracted_data_job', 'extracted_data', ['job_id', 'created_at'])
    op.create_index('idx_extracted_data_org_quality', 'extracted_data', ['organization_id', 'validation_data_quality_score'])
    
    op.create_table('compliance_logs',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=False, index=True),
        sa.Column('job_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('scraping_jobs.id', ondelete='SET NULL'), nullable=True, index=True),
        sa.Column('target_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('scraping_targets.id', ondelete='SET NULL'), nullable=True, index=True),
        sa.Column('event_type', sa.String(50), nullable=False, index=True),
        sa.Column('severity', sa.String(20), nullable=False, server_default='INFO'),
        sa.Column('robots_txt_check', postgresql.JSONB(), nullable=True),
        sa.Column('rate_limit_event', postgresql.JSONB(), nullable=True),
        sa.Column('pii_detection', postgresql.JSONB(), nullable=True),
        sa.Column('domain_policy', postgresql.JSONB(), nullable=True),
        sa.Column('request_url', sa.Text(), nullable=False),
        sa.Column('request_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('request_ip_address', sa.String(45), nullable=True),
        sa.Column('request_proxy_used', sa.String(500), nullable=True),
        sa.Column('request_user_agent', sa.String(500), nullable=True),
        sa.Column('request_headers', postgresql.JSONB(), server_default='{}'),
        sa.Column('response_status_code', sa.Integer(), nullable=True),
        sa.Column('response_action_taken', sa.String(100), nullable=True),
        sa.Column('response_reason', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('metadata', postgresql.JSONB(), server_default='{}'),
    )
    op.create_index('idx_compliance_logs_org_event', 'compliance_logs', ['organization_id', 'event_type'])
    op.create_index('idx_compliance_logs_timestamp', 'compliance_logs', ['created_at'])
    op.create_index('idx_compliance_logs_job', 'compliance_logs', ['job_id', 'created_at'])
    
    op.create_table('proxy_pools',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=False, index=True),
        sa.Column('name', sa.String(255), nullable=False),
        sa.Column('proxies', postgresql.JSONB(), server_default='[]'),
        sa.Column('rotation_strategy', sa.String(50), server_default='ROUND_ROBIN'),
        sa.Column('rotation_max_failures_before_quarantine', sa.Integer(), server_default='3'),
        sa.Column('rotation_quarantine_duration_minutes', sa.Integer(), server_default='60'),
        sa.Column('rotation_health_check_interval_minutes', sa.Integer(), server_default='5'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), onupdate=sa.text('now()'), nullable=False),
        sa.UniqueConstraint('organization_id', 'name', name='uq_proxy_pool_org_name'),
    )
    op.create_index('idx_proxy_pools_org', 'proxy_pools', ['organization_id', 'created_at'])
    
    # Add organization_id to existing crawl_queue table (will be replaced)
    # Actually we need to recreate crawl_queue for the new schema
    op.create_table('crawl_queue',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=False, index=True),
        sa.Column('job_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('scraping_jobs.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('url', sa.Text(), nullable=False),
        sa.Column('domain', sa.String(255), nullable=False, index=True),
        sa.Column('depth', sa.Integer(), server_default='0'),
        sa.Column('parent_url', sa.Text(), nullable=True),
        sa.Column('priority', sa.Integer(), server_default='5'),
        sa.Column('status', sa.String(50), server_default='PENDING', index=True),
        sa.Column('retry_count', sa.Integer(), server_default='0'),
        sa.Column('max_retries', sa.Integer(), server_default='3'),
        sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('last_error', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.UniqueConstraint('organization_id', 'job_id', 'url', name='uq_crawl_queue_org_job_url'),
    )
    op.create_index('idx_crawl_queue_org_job_status', 'crawl_queue', ['organization_id', 'job_id', 'status'])
    op.create_index('idx_crawl_queue_next_retry', 'crawl_queue', ['status', 'next_retry_at'])
    op.create_index('idx_crawl_queue_domain_priority', 'crawl_queue', ['domain', 'priority'])
    
    # Update robots_txt_cache to add organization_id
    op.add_column('robots_txt_cache', sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=False, server_default='00000000-0000-0000-0000-000000000001'))
    op.create_index('idx_robots_txt_cache_org', 'robots_txt_cache', ['organization_id', 'domain'])
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop new tables (reverse order)
    op.drop_index('idx_crawl_queue_domain_priority', table_name='crawl_queue')
    op.drop_index('idx_crawl_queue_next_retry', table_name='crawl_queue')
    op.drop_index('idx_crawl_queue_org_job_status', table_name='crawl_queue')
    op.drop_index('uq_crawl_queue_org_job_url', table_name='crawl_queue')
    op.drop_table('crawl_queue')
    
    op.drop_index('idx_robots_txt_cache_org', table_name='robots_txt_cache')
    op.drop_column('robots_txt_cache', 'organization_id')
    
    op.drop_index('idx_proxy_pools_org', table_name='proxy_pools')
    op.drop_index('uq_proxy_pool_org_name', table_name='proxy_pools')
    op.drop_table('proxy_pools')
    
    op.drop_index('idx_compliance_logs_job', table_name='compliance_logs')
    op.drop_index('idx_compliance_logs_timestamp', table_name='compliance_logs')
    op.drop_index('idx_compliance_logs_org_event', table_name='compliance_logs')
    op.drop_table('compliance_logs')
    
    op.drop_index('idx_extracted_data_org_quality', table_name='extracted_data')
    op.drop_index('idx_extracted_data_job', table_name='extracted_data')
    op.drop_table('extracted_data')
    
    op.drop_index('idx_raw_content_hash', table_name='raw_content')
    op.drop_index('idx_raw_content_org_domain', table_name='raw_content')
    op.drop_index('idx_raw_content_job_status', table_name='raw_content')
    op.drop_table('raw_content')
    
    op.drop_index('idx_job_errors_retryable', table_name='job_errors')
    op.drop_index('idx_job_errors_job_occurred', table_name='job_errors')
    op.drop_table('job_errors')
    
    op.drop_index('idx_job_stage_details_job_stage', table_name='job_stage_details')
    op.drop_index('uq_job_stage', table_name='job_stage_details')
    op.drop_table('job_stage_details')
    
    op.drop_index('idx_scraping_jobs_status_created', table_name='scraping_jobs')
    op.drop_index('idx_scraping_jobs_target', table_name='scraping_jobs')
    op.drop_index('idx_scraping_jobs_org_status', table_name='scraping_jobs')
    op.drop_table('scraping_jobs')
    
    op.drop_index('idx_scraping_targets_created', table_name='scraping_targets')
    op.drop_index('idx_scraping_targets_org_status', table_name='scraping_targets')
    op.drop_table('scraping_targets')
    
    # Recreate old tables
    op.create_table('crawl_jobs',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('job_type', sa.String(50), nullable=False, index=True),
        sa.Column('domain', sa.String(255), nullable=True, index=True),
        sa.Column('ticker', sa.String(20), nullable=True, index=True),
        sa.Column('status', sa.String(50), nullable=False, server_default='pending', index=True),
        sa.Column('priority', sa.String(20), nullable=False, server_default='medium'),
        sa.Column('depth', sa.Integer(), server_default='2'),
        sa.Column('max_pages', sa.Integer(), nullable=True),
        sa.Column('pages_crawled', sa.Integer(), server_default='0'),
        sa.Column('pages_total', sa.Integer(), nullable=True),
        sa.Column('config', postgresql.JSONB(), server_default='{}'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('retry_count', sa.Integer(), server_default='0'),
    )
    op.create_index('idx_crawl_jobs_status_created', 'crawl_jobs', ['status', 'created_at'])
    
    op.create_table('crawled_content',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('job_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('crawl_jobs.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('url', sa.Text(), nullable=False, unique=True, index=True),
        sa.Column('domain', sa.String(255), nullable=False, index=True),
        sa.Column('content_type', sa.String(50), nullable=True, index=True),
        sa.Column('title', sa.Text(), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('author', sa.String(255), nullable=True),
        sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('markdown_content', sa.Text(), nullable=True),
        sa.Column('raw_html_size_bytes', sa.Integer(), nullable=True),
        sa.Column('markdown_size_bytes', sa.Integer(), nullable=True),
        sa.Column('s3_path', sa.Text(), nullable=True),
        sa.Column('metadata', postgresql.JSONB(), server_default='{}'),
        sa.Column('extracted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('http_status', sa.Integer(), nullable=True),
        sa.Column('robots_allowed', sa.Boolean(), server_default='true'),
        sa.Column('noindex_present', sa.Boolean(), server_default='false'),
        sa.Column('pii_status', sa.String(20), server_default='clean', index=True),
        sa.Column('pii_scan_results', postgresql.JSONB(), server_default='{}'),
        sa.Column('is_deleted', sa.Boolean(), server_default='false', index=True),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('delete_reason', sa.String(100), nullable=True),
    )
    op.create_index('idx_crawled_content_job_type', 'crawled_content', ['job_id', 'content_type'])
    op.create_index('idx_crawled_content_domain_extracted', 'crawled_content', ['domain', 'extracted_at'])
    
    op.create_table('crawl_queue',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('job_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('crawl_jobs.id', ondelete='CASCADE'), nullable=False, index=True),
        sa.Column('url', sa.Text(), nullable=False),
        sa.Column('domain', sa.String(255), nullable=False, index=True),
        sa.Column('depth', sa.Integer(), server_default='0'),
        sa.Column('parent_url', sa.Text(), nullable=True),
        sa.Column('priority', sa.Integer(), server_default='5'),
        sa.Column('status', sa.String(50), server_default='pending', index=True),
        sa.Column('retry_count', sa.Integer(), server_default='0'),
        sa.Column('max_retries', sa.Integer(), server_default='3'),
        sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('last_error', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.UniqueConstraint('job_id', 'url', name='uq_crawl_queue_job_url'),
    )
    op.create_index('idx_crawl_queue_job_status', 'crawl_queue', ['job_id', 'status'])
    op.create_index('idx_crawl_queue_next_retry', 'crawl_queue', ['status', 'next_retry_at'])
    op.create_index('idx_crawl_queue_domain_priority', 'crawl_queue', ['domain', 'priority'])
    
    op.create_table('audit_logs',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('job_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('crawl_jobs.id', ondelete='SET NULL'), nullable=True),
        sa.Column('content_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('crawled_content.id', ondelete='SET NULL'), nullable=True),
        sa.Column('url', sa.Text(), nullable=False),
        sa.Column('domain', sa.String(255), nullable=False, index=True),
        sa.Column('action', sa.String(50), nullable=False, index=True),
        sa.Column('ip_address', sa.String(45), nullable=True),
        sa.Column('user_agent', sa.String(500), nullable=True),
        sa.Column('http_status', sa.Integer(), nullable=True),
        sa.Column('bytes_downloaded', sa.Integer(), nullable=True),
        sa.Column('duration_ms', sa.Integer(), nullable=True),
        sa.Column('outcome', sa.String(50), nullable=False),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, index=True),
        sa.Column('details', postgresql.JSONB(), server_default='{}'),
    )
    op.create_index('idx_audit_logs_timestamp', 'audit_logs', ['timestamp'])
    op.create_index('idx_audit_logs_domain_action', 'audit_logs', ['domain', 'action'])
    
    # ### end Alembic commands ###
