apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: value-fabric-gateway
  namespace: value-fabric
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  gatewayClassName: envoy-gateway
  listeners:
    - name: http-frontend
      protocol: HTTP
      port: 80
      hostname: __HOST__
      allowedRoutes:
        namespaces:
          from: Same
    - name: https-frontend
      protocol: HTTPS
      port: 443
      hostname: __HOST__
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: frontend-tls
      allowedRoutes:
        namespaces:
          from: Same
    - name: http-api
      protocol: HTTP
      port: 80
      hostname: __API_HOST__
      allowedRoutes:
        namespaces:
          from: Same
    - name: https-api
      protocol: HTTPS
      port: 443
      hostname: __API_HOST__
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: layer-apis-tls
      allowedRoutes:
        namespaces:
          from: Same
