/**
 * Screen 9 — Business Case Viewer
 * Design: Refined Enterprise SaaS
 */
import { Download, Share2, Eye } from "lucide-react";
import { PageHeader, Btn, SectionCard, EntityBadge, DataTable } from "@/components/WfPrimitives";

const USE_CASES = [
  {
    name: "Automated Pipeline Forecasting",
    persona: "Sales Director",
    driver: "Revenue Enhancement",
    roi: "$2.4M",
    payback: "6 mo",
    confidence: 91,
  },
  {
    name: "Touchless Accounts Payable",
    persona: "CFO",
    driver: "Cost Reduction",
    roi: "$1.1M",
    payback: "9 mo",
    confidence: 87,
  },
  {
    name: "Predictive Maintenance",
    persona: "IT Operations Manager",
    driver: "Risk Mitigation",
    roi: "$780K",
    payback: "12 mo",
    confidence: 83,
  },
  {
    name: "Customer Churn Reduction",
    persona: "Customer Success VP",
    driver: "Revenue Retention",
    roi: "$900K",
    payback: "8 mo",
    confidence: 94,
  },
];

export default function BusinessCase() {
  return (
    <div className="p-6 max-w-5xl">
      <PageHeader
        breadcrumbs={["Agent Workflows", "Business Cases"]}
        title="Business Case: Acme Corp"
        subtitle="Generated by BusinessCaseGenerator-v3.0 · 2 mins ago"
        actions={
          <>
            <Btn variant="ghost"><Download size={12}/> Export PDF</Btn>
            <Btn variant="ghost"><Share2 size={12}/> Share</Btn>
          </>
        }
      />

      {/* Hero ROI card */}
      <div className="bg-gradient-to-br from-blue-700 to-blue-900 rounded-xl p-6 mb-6 text-white shadow-lg">
        <div className="text-[11px] font-bold uppercase tracking-wider opacity-70 mb-1">Total Estimated Value</div>
        <div className="text-[48px] font-extrabold leading-none mb-1">$5.18M</div>
        <div className="text-[13px] opacity-80">Across 4 use cases · Avg. payback 8.75 months</div>
        <div className="flex gap-6 mt-4">
          <div>
            <div className="text-[10px] uppercase tracking-wider opacity-60">Confidence</div>
            <div className="text-[18px] font-bold">89%</div>
          </div>
          <div>
            <div className="text-[10px] uppercase tracking-wider opacity-60">Use Cases</div>
            <div className="text-[18px] font-bold">4</div>
          </div>
          <div>
            <div className="text-[10px] uppercase tracking-wider opacity-60">Personas</div>
            <div className="text-[18px] font-bold">4</div>
          </div>
          <div>
            <div className="text-[10px] uppercase tracking-wider opacity-60">Value Drivers</div>
            <div className="text-[18px] font-bold">3</div>
          </div>
        </div>
      </div>

      {/* Use case breakdown */}
      <SectionCard title="Use Case Breakdown" noPad className="mb-5">
        <DataTable
          columns={["Use Case", "Persona", "Value Driver", "Est. ROI", "Payback", "Confidence", "Actions"]}
          rows={USE_CASES.map(uc => [
            <span className="font-semibold text-neutral-800">{uc.name}</span>,
            <EntityBadge type="persona" label={uc.persona}/>,
            <EntityBadge type="valuedriver" label={uc.driver}/>,
            <span className="font-bold text-emerald-700">{uc.roi}</span>,
            <span className="text-neutral-600 text-[11px]">{uc.payback}</span>,
            <div className="flex items-center gap-2">
              <div className="h-1.5 w-16 bg-neutral-100 rounded-full overflow-hidden">
                <div className="h-full bg-blue-500 rounded-full" style={{ width: `${uc.confidence}%` }}/>
              </div>
              <span className={`text-[11px] font-semibold ${uc.confidence >= 90 ? "text-emerald-700" : "text-amber-700"}`}>
                {uc.confidence}%
              </span>
            </div>,
            <div className="flex gap-2">
              <Btn variant="ghost" className="text-[11px]"><Eye size={10}/> View Trace</Btn>
            </div>,
          ])}
        />
      </SectionCard>

      {/* Executive narrative */}
      <SectionCard title="Executive Summary">
        <div className="prose prose-sm max-w-none text-neutral-700 text-[13px] leading-relaxed">
          <p>
            Acme Corp presents a compelling opportunity for value realization across four high-confidence use cases.
            The most significant driver is <strong>Automated Pipeline Forecasting</strong>, which leverages the
            existing CRM Integration and Predictive Analytics capabilities to deliver an estimated <strong>$2.4M</strong> in
            incremental revenue within six months of deployment.
          </p>
          <p className="mt-3">
            The CFO persona stands to benefit from <strong>Touchless Accounts Payable</strong> automation,
            reducing manual processing costs by an estimated 60% and achieving payback within nine months.
            Combined with the Customer Churn Reduction initiative — which carries the highest confidence score
            at 94% — the total addressable value fabric for Acme Corp is estimated at <strong>$5.18M annually</strong>.
          </p>
        </div>
      </SectionCard>
    </div>
  );
}
