/**
 * Screen 9 — Business Case Viewer
 * Design: Refined Enterprise SaaS
 */
import { useState } from "react";
import { Download, Share2, Eye, Loader2 } from "lucide-react";
import { useSearchParams } from "wouter";
import { PageHeader, Btn, SectionCard, EntityBadge, DataTable } from "@/components/WfPrimitives";
import { useBusinessCase, useDocumentExport, downloadExport } from "@/hooks/useDocuments";

export default function BusinessCase() {
  const [searchParams] = useSearchParams();
  const businessCaseId = searchParams.get("id") || "default";
  const [isExporting, setIsExporting] = useState(false);

  const { data: businessCase, isLoading, error } = useBusinessCase(businessCaseId);
  const exportMutation = useDocumentExport();

  const handleExportPDF = async () => {
    if (!businessCase) return;
    setIsExporting(true);
    try {
      const result = await exportMutation.mutateAsync({
        document_type: "business_case",
        business_case_id: businessCaseId,
        format: "pdf",
        include_provenance: true,
      });

      if (result.download_url) {
        downloadExport(result.download_url, result.download_url.split("/").pop() || "business_case.pdf");
      }
    } finally {
      setIsExporting(false);
    }
  };

  const handleViewTrace = (useCaseId: string) => {
    // Navigate to DecisionTrace with entity ID
    window.location.href = `/decision-trace?entityId=${encodeURIComponent(useCaseId)}`;
  };

  if (isLoading) {
    return (
      <div className="p-6 max-w-5xl flex items-center justify-center h-64">
        <Loader2 className="animate-spin text-blue-600" size={32} />
      </div>
    );
  }

  if (error || !businessCase) {
    return (
      <div className="p-6 max-w-5xl">
        <div className="bg-red-50 border border-red-200 rounded-lg p-4 text-red-700">
          Failed to load business case. Please try again.
        </div>
      </div>
    );
  }

  const useCases = businessCase.use_cases || [];

  return (
    <div className="p-6 max-w-5xl">
      <PageHeader
        breadcrumbs={["Agent Workflows", "Business Cases"]}
        title={businessCase.title || "Business Case"}
        subtitle={`Generated by ${businessCase.generator} · ${new Date(businessCase.created_at).toLocaleDateString()}`}
        actions={
          <>
            <Btn
              variant="ghost"
              onClick={handleExportPDF}
              disabled={isExporting}
            >
              {isExporting ? <Loader2 size={12} className="animate-spin" /> : <Download size={12} />}
              Export PDF
            </Btn>
            <Btn variant="ghost"><Share2 size={12}/> Share</Btn>
          </>
        }
      />

      {/* Hero ROI card */}
      <div className="bg-gradient-to-br from-blue-700 to-blue-900 rounded-xl p-6 mb-6 text-white shadow-lg">
        <div className="text-[11px] font-bold uppercase tracking-wider opacity-70 mb-1">Total Estimated Value</div>
        <div className="text-[48px] font-extrabold leading-none mb-1">{businessCase.total_value}</div>
        <div className="text-[13px] opacity-80">
          Across {businessCase.use_case_count} use cases · Avg. payback: {businessCase.avg_payback}
        </div>
        <div className="flex gap-6 mt-4">
          <div>
            <div className="text-[10px] uppercase tracking-wider opacity-60">Confidence</div>
            <div className="text-[18px] font-bold">{businessCase.avg_confidence}%</div>
          </div>
          <div>
            <div className="text-[10px] uppercase tracking-wider opacity-60">Use Cases</div>
            <div className="text-[18px] font-bold">{businessCase.use_case_count}</div>
          </div>
          <div>
            <div className="text-[10px] uppercase tracking-wider opacity-60">Personas</div>
            <div className="text-[18px] font-bold">{businessCase.persona_count}</div>
          </div>
          <div>
            <div className="text-[10px] uppercase tracking-wider opacity-60">Value Drivers</div>
            <div className="text-[18px] font-bold">{businessCase.driver_count}</div>
          </div>
        </div>
      </div>

      {/* Use case breakdown */}
      <SectionCard title="Use Case Breakdown" noPad className="mb-5">
        <DataTable
          columns={["Use Case", "Persona", "Value Driver", "Est. ROI", "Payback", "Confidence", "Actions"]}
          rows={useCases.map((uc) => [
            <span className="font-semibold text-neutral-800" key="name">{uc.name}</span>,
            <EntityBadge type="persona" label={uc.persona} key="persona" />,
            <EntityBadge type="valuedriver" label={uc.driver} key="driver" />,
            <span className="font-bold text-emerald-700" key="roi">{uc.roi}</span>,
            <span className="text-neutral-600 text-[11px]" key="payback">{uc.payback}</span>,
            <div className="flex items-center gap-2" key="confidence">
              <div className="h-1.5 w-16 bg-neutral-100 rounded-full overflow-hidden">
                <div className="h-full bg-blue-500 rounded-full" style={{ width: `${uc.confidence}%` }} />
              </div>
              <span className={`text-[11px] font-semibold ${uc.confidence >= 90 ? "text-emerald-700" : "text-amber-700"}`}>
                {uc.confidence}%
              </span>
            </div>,
            <div className="flex gap-2" key="actions">
              <Btn
                variant="ghost"
                className="text-[11px]"
                onClick={() => handleViewTrace(uc.id)}
              >
                <Eye size={10} /> View Trace
              </Btn>
            </div>,
          ])}
        />
      </SectionCard>

      {/* Executive narrative */}
      <SectionCard title="Executive Summary">
        <div
          className="prose prose-sm max-w-none text-neutral-700 text-[13px] leading-relaxed"
          dangerouslySetInnerHTML={{ __html: businessCase.executive_summary }}
        />
      </SectionCard>
    </div>
  );
}
