"""Models package for Layer 4 Agentic Workflow Engine."""

from .agent_state import (
    AgentState,
    BaseAgentState,
    BusinessCaseAgentState,
    BusinessCaseInputData,
    BusinessCaseSection,
    GapAnalysis,
    OrchestratorAgentState,
    ROIAgentState,
    ROIInputData,
    ROIResult,
    WhitespaceAgentState,
    WhitespaceInputData,
    WorkflowStatus,
    WorkflowType,
)
from .workflow_config import (
    BUSINESS_CASE_WORKFLOW_CONFIG,
    EdgeConfig,
    EdgeType,
    NodeConfig,
    NodeType,
    ROI_WORKFLOW_CONFIG,
    WHITESPACE_WORKFLOW_CONFIG,
    WorkflowConfig,
)
from .tool_schemas import (
    ToolCategory,
    ToolSchema,
    # Knowledge tools
    QueryGraphInput,
    QueryGraphOutput,
    SemanticSearchInput,
    SemanticSearchOutput,
    GetEntityInput,
    GetEntityOutput,
    # Calculation tools
    EvaluateFormulaInput,
    EvaluateFormulaOutput,
    CalculateROIInput,
    CalculateROIOutput,
    CompareBenchmarksInput,
    CompareBenchmarksOutput,
    # CRM tools
    GetProspectDataInput,
    GetProspectDataOutput,
    UpdateOpportunityInput,
    UpdateOpportunityOutput,
    # Generation tools
    GenerateSectionInput,
    GenerateSectionOutput,
    AssembleDocumentInput,
    AssembleDocumentOutput,
    # Integration tools
    SendNotificationInput,
    SendNotificationOutput,
    # Utility tools
    ValidateInputInput,
    ValidateInputOutput,
)

__all__ = [
    # Agent State
    "AgentState",
    "BaseAgentState",
    "WorkflowStatus",
    "WorkflowType",
    "ROIAgentState",
    "ROIInputData",
    "ROIResult",
    "WhitespaceAgentState",
    "WhitespaceInputData",
    "GapAnalysis",
    "BusinessCaseAgentState",
    "BusinessCaseInputData",
    "BusinessCaseSection",
    "OrchestratorAgentState",
    # Workflow Config
    "WorkflowConfig",
    "NodeConfig",
    "EdgeConfig",
    "NodeType",
    "EdgeType",
    "ROI_WORKFLOW_CONFIG",
    "WHITESPACE_WORKFLOW_CONFIG",
    "BUSINESS_CASE_WORKFLOW_CONFIG",
    # Tool Schemas
    "ToolCategory",
    "ToolSchema",
    "QueryGraphInput",
    "QueryGraphOutput",
    "SemanticSearchInput",
    "SemanticSearchOutput",
    "GetEntityInput",
    "GetEntityOutput",
    "EvaluateFormulaInput",
    "EvaluateFormulaOutput",
    "CalculateROIInput",
    "CalculateROIOutput",
    "CompareBenchmarksInput",
    "CompareBenchmarksOutput",
    "GetProspectDataInput",
    "GetProspectDataOutput",
    "UpdateOpportunityInput",
    "UpdateOpportunityOutput",
    "GenerateSectionInput",
    "GenerateSectionOutput",
    "AssembleDocumentInput",
    "AssembleDocumentOutput",
    "SendNotificationInput",
    "SendNotificationOutput",
    "ValidateInputInput",
    "ValidateInputOutput",
]
