"""API module for Layer 3 Knowledge Graph."""

from .dependencies import (
    AppState,
    get_app_state,
    get_centrality_analyzer,
    get_community_detector,
    get_graph_rag,
    get_hybrid_search,
    get_neo4j_driver,
    get_schema_initializer,
    get_settings_from_state,
    get_similarity_analyzer,
    get_sync_manager,
    get_vector_store,
)
from .main import app
from .models import (
    CentralityRequest,
    CentralityResponse,
    CommunityDetectionRequest,
    CommunityDetectionResponse,
    EntityComparisonRequest,
    EntityComparisonResponse,
    EntityContextResponse,
    GraphRAGQuery,
    GraphRAGResponse,
    HealthResponse,
    IngestRequest,
    IngestResponse,
    SchemaStatistics,
    SchemaStatus,
    SearchRequest,
    SearchResponse,
    SimilarityRequest,
    SimilarityResponse,
    SyncStatusResponse,
    ValueTreeResponse,
)

__all__ = [
    "app",
    "AppState",
    "get_app_state",
    "get_centrality_analyzer",
    "get_community_detector",
    "get_graph_rag",
    "get_hybrid_search",
    "get_neo4j_driver",
    "get_schema_initializer",
    "get_settings_from_state",
    "get_similarity_analyzer",
    "get_sync_manager",
    "get_vector_store",
    # Models
    "CentralityRequest",
    "CentralityResponse",
    "CommunityDetectionRequest",
    "CommunityDetectionResponse",
    "EntityComparisonRequest",
    "EntityComparisonResponse",
    "EntityContextResponse",
    "GraphRAGQuery",
    "GraphRAGResponse",
    "HealthResponse",
    "IngestRequest",
    "IngestResponse",
    "SchemaStatistics",
    "SchemaStatus",
    "SearchRequest",
    "SearchResponse",
    "SimilarityRequest",
    "SimilarityResponse",
    "SyncStatusResponse",
    "ValueTreeResponse",
]
